export interface IIconifyIcon {
  userFriendlyName: string;
  variations: string[];
  keywords: string[];
}

const icons: IIconifyIcon[] = [
  {
    userFriendlyName: "WhatsApp",
    variations: [
      "logos:whatsapp",
      "dashicons:whatsapp",
      "fa-brands:whatsapp",
      "uil:whatsapp-alt",
    ],
    keywords: ["whatsapp", "wpp", "zap", "zapzap", "zap zap"],
  },
  {
    userFriendlyName: "TikTok",
    variations: [
      "ic:baseline-tiktok",
      "ph:tiktok-logo-light",
      "iconoir:tiktok",
      "logos:tiktok",
      "logos:tiktok-icon",
    ],
    keywords: ["tiktok", "tik", "tok"],
  },
  {
    userFriendlyName: "Instagram",
    variations: [
      "ant-design:instagram-outlined",
      "ant-design:instagram-filled",
      "entypo-social:instagram-with-circle",
      "fa-brands:instagram-square",
      "icomoon-free:instagram",
      "logos:instagram",
    ],
    keywords: ["instagram", "insta"],
  },
  {
    userFriendlyName: "Facebook",
    variations: [
      "bi:facebook",
      "entypo-social:facebook",
      "bx:bxl-facebook",
      "iconoir:facebook",
    ],
    keywords: ["facebook", "face", "fb", "book"],
  },
  {
    userFriendlyName: "Email",
    variations: [
      "carbon:email",
      "clarity:email-line",
      "clarity:email-solid",
      "ic:round-email",
      "fxemoji:email",
      "ic:sharp-alternate-email",
      "icon-park:email-block",
    ],
    keywords: ["email", "e-mail", "mail", "@", "message", "mensagem", "msg"],
  },
  {
    userFriendlyName: "Twitter",
    variations: [
      "akar-icons:twitter-fill",
      "logos:twitter",
      "entypo-social:twitter-with-circle",
      "et:twitter",
      "fa-brands:twitter-square",
    ],
    keywords: ["twitter"],
  },
  {
    userFriendlyName: "YouTube",
    variations: [
      "akar-icons:youtube-fill",
      "ant-design:youtube-outlined",
      "foundation:social-youtube",
      "entypo-social:youtube-with-circle",
      "logos:youtube",
      "openmoji:youtube",
      "entypo-social:youtube-with-circle",
      "fa-brands:youtube-square",
    ],
    keywords: ["youtube", "yt", "you", "tube", "video", "vídeo"],
  },
  {
    userFriendlyName: "Phone",
    variations: [
      "akar-icons:phone",
      "ant-design:phone-filled",
      "carbon:phone-voice-filled",
      "carbon:phone-voice",
      "bi:phone",
      "bi:phone-fill",
      "carbon:phone-ip",
    ],
    keywords: [
      "phone",
      "fone",
      "telefone",
      "celphone",
      "smartphone",
      "tel",
      "call",
      "ring",
    ],
  },
  {
    userFriendlyName: "Spotify",
    variations: [
      "akar-icons:spotify-fill",
      "logos:spotify-icon",
      "logos:spotify",
      "simple-line-icons:social-spotify",
    ],
    keywords: ["spotify", "spot"],
  },
  {
    userFriendlyName: "Website",
    variations: [
      "whh:website",
      "dashicons:whatsapp",
      "fa-brands:whatsapp",
      "uil:whatsapp-alt",
    ],
    keywords: [
      "website",
      "web",
      "site",
      "url",
      "link",
      "domain",
      "domínio",
      "dominio",
    ],
  },
  {
    userFriendlyName: "LinkedIn",
    variations: [
      "akar-icons:linkedin-fill",
      "entypo-social:linkedin-with-circle",
      "et:linkedin",
      "fa-brands:linkedin-in",
      "logos:linkedin",
      "logos:linkedin-icon",
    ],
    keywords: ["linkedin", "in"],
  },
  {
    userFriendlyName: "Twitch",
    variations: [
      "akar-icons:twitch-fill",
      "ph:twitch-logo-fill",
      "ph:twitch-logo-light",
      "logos:twitch",
    ],
    keywords: ["twitch"],
  },
  {
    userFriendlyName: "Discord",
    variations: [
      "akar-icons:discord-fill",
      "bx:bxl-discord",
      "logos:discord",
      "logos:discord-icon",
    ],
    keywords: ["discord"],
  },
  {
    userFriendlyName: "Telegram",
    variations: [
      "akar-icons:telegram-fill",
      "bx:bxl-telegram",
      "la:telegram",
      "logos:telegram",
    ],
    keywords: ["telegram"],
  },
  {
    userFriendlyName: "Snapchat",
    variations: [
      "akar-icons:snapchat-fill",
      "bi:snapchat",
      "fa:snapchat-square",
      "fa:snapchat",
    ],
    keywords: ["snapchat"],
  },
  {
    userFriendlyName: "Pinterest",
    variations: [
      "akar-icons:pinterest-fill",
      "bx:bxl-pinterest-alt",
      "fa-brands:pinterest-square",
      "logos:pinterest",
    ],
    keywords: ["pinterest"],
  },
  {
    userFriendlyName: "Shop",
    variations: [
      "ant-design:shop-filled",
      "ant-design:shop-outlined",
      "flat-color-icons:shop",
      "grommet-icons:shop",
    ],
    keywords: [
      "shop",
      "shopping",
      "loja",
      "compra",
      "compras",
      "comprar",
      "produto",
      "products",
    ],
  },
  {
    userFriendlyName: "SoundCloud",
    variations: [
      "akar-icons:soundcloud-fill",
      "icomoon-free:soundcloud2",
      "logos:soundcloud",
    ],
    keywords: ["soundcloud"],
  },
  {
    userFriendlyName: "Messenger",
    variations: ["bi:messenger", "teenyicons:messenger-outline"],
    keywords: ["messenger"],
  },
  {
    userFriendlyName: "Apple Music",
    variations: ["cib:apple-music"],
    keywords: ["apple", "music", "apple music"],
  },
  {
    userFriendlyName: "PayPal",
    variations: [
      "bi:paypal",
      "bx:bxl-paypal",
      "cib:cc-paypal",
      "fontisto:paypal",
      "logos:paypal",
    ],
    keywords: ["paypal"],
  },
  {
    userFriendlyName: "Line",
    variations: ["bi:line"],
    keywords: ["line"],
  },
  {
    userFriendlyName: "Amazon",
    variations: [
      "ant-design:amazon-circle-filled",
      "ant-design:amazon-outlined",
      "ant-design:amazon-square-filled",
      "cib:amazon-aws",
      "cib:amazon-pay",
      "cib:cc-amazon-pay",
    ],
    keywords: ["amazon", "amazon pay"],
  },
  {
    userFriendlyName: "Deezer",
    variations: ["fa-brands:deezer", "jam:deezer-circle", "jam:deezer-square"],
    keywords: ["deezer"],
  },
  {
    userFriendlyName: "Behance",
    variations: [
      "ant-design:behance-circle-filled",
      "ant-design:behance-outlined",
      "ant-design:behance-square-filled",
      "logos:behance",
    ],
    keywords: ["behance"],
  },
  {
    userFriendlyName: "Tumblr",
    variations: [
      "akar-icons:tumblr-fill",
      "brandico:tumblr-rect",
      "el:tumblr",
      "entypo-social:tumblr-with-circle",
      "logos:tumblr",
    ],
    keywords: ["tumblr"],
  },
  {
    userFriendlyName: "Steam",
    variations: [
      "bi:steam",
      "fa-brands:steam-square",
      "icomoon-free:steam",
      "la:steam",
    ],
    keywords: ["steam"],
  },
  {
    userFriendlyName: "Onlyfans",
    variations: ["simple-icons:onlyfans"],
    keywords: ["xxxxxxx", "xxxxxxx"],
  },
  {
    userFriendlyName: "Google Drive",
    variations: [
      "uil:google-drive",
      "mdi:folder-google-drive",
      "logos:google-drive",
      "uit:google-drive-alt",
    ],
    keywords: ["google", "drive", "google drive"],
  },
  {
    userFriendlyName: "Wattpad",
    variations: ["cib:wattpad", "simple-icons:wattpad"],
    keywords: ["wattpad", "watt"],
  },
  {
    userFriendlyName: "Etsy",
    variations: ["bx:bxl-etsy", "cib:etsy"],
    keywords: ["etsy"],
  },
  {
    userFriendlyName: "Shopify",
    variations: [
      "bx:bxl-shopify",
      "jam:shopify-circle",
      "jam:shopify-square",
      "logos:shopify",
    ],
    keywords: ["shopify", "Shop"],
  },
  {
    userFriendlyName: "Reddit",
    variations: [
      "ant-design:reddit-circle-filled",
      "ant-design:reddit-square-filled",
      "ant-design:reddit-outlined",
      "dashicons:reddit",
      "logos:reddit",
      "flat-color-icons:reddit",
      "logos:reddit-icon",
    ],
    keywords: ["reddit", "red"],
  },
  {
    userFriendlyName: "Viber",
    variations: [
      "cib:viber",
      "jam:viber-circle",
      "jam:viber-square",
      "whh:viber",
      "whh:squareviber",
    ],
    keywords: ["viber", "vibe"],
  },
  {
    userFriendlyName: "Goodreads",
    variations: ["cib:goodreads", "fa-brands:goodreads", "la:goodreads"],
    keywords: ["goodreads", "good", "reads"],
  },
  {
    userFriendlyName: "Skype",
    variations: [
      "ant-design:skype-filled",
      "ant-design:skype-outlined",
      "jam:skype-circle",
      "jam:skype-square",
      "logos:skype",
      "entypo-social:skype-with-circle",
    ],
    keywords: ["skype", "sky"],
  },
  {
    userFriendlyName: "Medium",
    variations: [
      "akar-icons:medium-fill",
      "ant-design:medium-circle-filled",
      "ant-design:medium-square-filled",
      "ant-design:medium-workmark-outlined",
    ],
    keywords: ["medium", "med"],
  },
  {
    userFriendlyName: "Google Play",
    variations: [
      "ph:google-play-logo-light",
      "ri:google-play-fill",
      "jam:google-play-circle",
      "jam:google-play-square",
      "logos:google-play",
      "logos:google-play-icon",
    ],
    keywords: ["google", "play", "google play"],
  },
  {
    userFriendlyName: "Vimeo",
    variations: [
      "akar-icons:vimeo-fill",
      "brandico:vimeo-rect",
      "entypo-social:vimeo-with-circle",
      "jam:vimeo-circle",
      "jam:vimeo-square",
      "logos:vimeo",
      "logos:vimeo-icon",
    ],
    keywords: ["vimeo"],
  },
  {
    userFriendlyName: "Patreon",
    variations: [
      "bx:bxl-patreon",
      "jam:patreon-circle",
      "jam:patreon-square",
      "la:patreon",
      "logos:patreon",
    ],
    keywords: ["patreon"],
  },
  {
    userFriendlyName: "Bandcamp",
    variations: ["brandico:bandcamp", "fa-brands:bandcamp", "la:bandcamp"],
    keywords: ["bandcamp", "band", "camp"],
  },
  {
    userFriendlyName: "VSCO",
    variations: ["cib:vsco"],
    keywords: ["vsco"],
  },
  {
    userFriendlyName: "VK",
    variations: [
      "akar-icons:vk-fill",
      "cib:vk",
      "entypo-social:vk-with-circle",
      "uit:vk-alt",
    ],
    keywords: ["vk"],
  },
  {
    userFriendlyName: "ApplePodcast",
    variations: ["simple-icons:applepodcasts"],
    keywords: ["applepodcasts", "apple", "podcast", "podcasts"],
  },
  {
    userFriendlyName: "WeChat",
    variations: [
      "ant-design:wechat-filled",
      "ri:wechat-2-fill",
      "ri:wechat-2-line",
      "xxxxxxx",
    ],
    keywords: ["wechat", "we", "chat"],
  },
  {
    userFriendlyName: "Mixcloud",
    variations: ["cib:mixcloud", "simple-icons:mixcloud"],
    keywords: ["mixcloud", "mix", "cloud"],
  },
  {
    userFriendlyName: "AppStore",
    variations: [
      "ion:logo-apple-appstore",
      "simple-icons:appstore",
      "tabler:brand-appstore",
      "uiw:appstore",
      "uiw:appstore-o",
    ],
    keywords: ["apple", "appstore", "app", "store", "loja"],
  },
  {
    userFriendlyName: "Napster",
    variations: [
      "xxxfa-brands:napsterxxxx",
      "jam:napster-circle",
      "jam:napster-square",
    ],
    keywords: ["napster", "nap", "naps"],
  },
  {
    userFriendlyName: "Flickr",
    variations: [
      "bx:bxl-flickr",
      "fa-brands:flickr",
      "entypo-social:flickr-with-circle",
      "logos:flickr",
    ],
    keywords: ["flickr", "flic"],
  },
  {
    userFriendlyName: "Ebay",
    variations: ["bx:bxl-ebay", "grommet-icons:ebay", "xxxxxxx", "xxxxxxx"],
    keywords: [
      "ebay",
      "loja",
      "market place",
      "market",
      "marketplace",
      "mercado",
      "loja",
    ],
  },
  {
    userFriendlyName: "Flipboard",
    variations: [
      "cib:flipboard",
      "fontisto:flipboard",
      "la:flipboard",
      "whh:flipboard",
    ],
    keywords: ["flipboard", "flip", "board"],
  },
  {
    userFriendlyName: "Last.FM",
    variations: [
      "brandico:lastfm",
      "brandico:lastfm-rect",
      "entypo-social:lastfm-with-circle",
      "logos:lastfm",
    ],
    keywords: ["lastfm", "last", "fm"],
  },
  {
    userFriendlyName: "Weibo",
    variations: [
      "ant-design:weibo-circle-filled",
      "ant-design:weibo-outlined",
      "ant-design:weibo-square-filled",
    ],
    keywords: ["weibo", "wei"],
  },
  {
    userFriendlyName: "Digg",
    variations: ["bx:bxl-digg", "whh:digg"],
    keywords: ["digg", "dig"],
  },
  {
    userFriendlyName: "Buy me a coffee",
    variations: ["cib:buy-me-a-coffee"],
    keywords: [
      "buy",
      "me",
      "coffee",
      "coffe",
      "cofe",
      "cofee",
      "café",
      "café",
      "buy me",
      "buy me a",
      "buy me a coffee",
      "copo",
      "cup",
    ],
  },
  {
    userFriendlyName: "Venmo",
    variations: ["bx:bxl-venmo", "cib:venmo", "ion:logo-venmo"],
    keywords: ["venmo"],
  },
  {
    userFriendlyName: "Zelle",
    variations: ["simple-icons:zelle"],
    keywords: ["zelle"],
  },
  {
    userFriendlyName: "Letterboxd",
    variations: ["cib:letterboxd"],
    keywords: ["letterboxd"],
  },
  {
    userFriendlyName: "Blogger",
    variations: [
      "brandico:blogger",
      "brandico:blogger-rect",
      "jam:blogger-circle",
      "jam:blogger-square",
      "logos:blogger",
    ],
    keywords: ["blogger", "blog"],
  },
  {
    userFriendlyName: "Artstation",
    variations: ["cib:artstation"],
    keywords: ["artstation"],
  },
  {
    userFriendlyName: "Amazon Prime",
    variations: ["simple-icons:amazonprime", "xxxxxxx", "xxxxxxx", "xxxxxxx"],
    keywords: ["amazon arime", "amazon", "prime"],
  },
  {
    userFriendlyName: "Google Maps",
    variations: ["logos:google-maps", "mdi:google-maps", "zmdi:google-maps"],
    keywords: [
      "google",
      "maps",
      "google maps",
      "map",
      "mapa",
      "location",
      "localization",
      "localização",
      "local",
      "coordenadas",
      "coordinates",
      "place",
      "address",
      "endereço",
    ],
  },
  {
    userFriendlyName: "Waze",
    variations: ["fa-brands:waze"],
    keywords: ["waze"],
  },
  {
    userFriendlyName: "Uber",
    variations: ["cib:uber", "fa-brands:uber", "la:uber", "simple-icons:uber"],
    keywords: ["uber"],
  },
  {
    userFriendlyName: "Uber Eats",
    variations: ["simple-icons:ubereats"],
    keywords: ["uber", "eats", "eat"],
  },
  {
    userFriendlyName: "Roblox",
    variations: ["simple-icons:roblox"],
    keywords: ["roblox"],
  },
  {
    userFriendlyName: "Google Podcast",
    variations: ["mdi:google-podcast", "ph:google-podcasts-logo-light"],
    keywords: ["google", "podcast", "google podcast", "podcasts"],
  },
  {
    userFriendlyName: "GitHub",
    variations: [
      "akar-icons:github-fill",
      "akar-icons:github-outline-fill",
      "brandico:github",
      "brandico:github-text",
      "fa-brands:github-square",
      "jam:github",
    ],
    keywords: ["github", "git", "hub"],
  },
  {
    userFriendlyName: "Git",
    variations: ["bi:git", "bx:bx-git-branch", "fa-brands:git-square"],
    keywords: ["git"],
  },
  {
    userFriendlyName: "XXXX",
    variations: ["xxxxxxx", "xxxxxxx", "xxxxxxx", "xxxxxxx"],
    keywords: ["xxxxxxx", "xxxxxxx"],
  },
  {
    userFriendlyName: "Redbubble",
    variations: ["bx:bxl-redbubble"],
    keywords: ["redbubble", "red", "bubble", "buble"],
  },
  {
    userFriendlyName: "Fiverr",
    variations: [
      "jam:fiverr",
      "jam:fiverr-circle",
      "jam:fiverr-square",
      "simple-icons:fiverr",
    ],
    keywords: ["fiverr", "five", "fiver"],
  },
  {
    userFriendlyName: "Coinbase",
    variations: ["simple-icons:coinbase"],
    keywords: ["coinbase", "coin", "base"],
  },
  {
    userFriendlyName: "Bitcoin",
    variations: [
      "akar-icons:bitcoin-fill",
      "bi:currency-bitcoin",
      "bx:bxl-bitcoin",
      "whh:bitcoinsquare",
      "logos:bitcoin",
    ],
    keywords: [
      "bitcoin",
      "bit",
      "coin",
      "crypto",
      "currency",
      "moeda",
      "cripto",
      "criptomoeda",
    ],
  },
  {
    userFriendlyName: "Nubank",
    variations: ["simple-icons:nubank"],
    keywords: ["nubank", "nu", "bank", "banco"],
  },
  {
    userFriendlyName: "Wordpress",
    variations: [
      "bi:wordpress",
      "brandico:wordpress",
      "cib:wordpress",
      "logos:wordpress",
    ],
    keywords: ["wordpress", "word", "press"],
  },
  {
    userFriendlyName: "Bank",
    variations: [
      "ant-design:bank-filled",
      "ant-design:bank-outlined",
      "bi:piggy-bank",
      "bi:piggy-bank-fill",
    ],
    keywords: ["bank", "piggy"],
  },
  {
    userFriendlyName: "Generic Currency",
    variations: [
      "bi:currency-dollar",
      "bi:currency-euro",
      "bi:currency-yen",
      "grommet-icons:currency",
    ],
    keywords: ["currency", "moeda"],
  },
  {
    userFriendlyName: "Dollar",
    variations: [
      "ant-design:dollar-circle-filled",
      "ant-design:dollar-circle-outlined",
      "bx:bxs-badge-dollar",
      "healthicons:dollar-negative",
    ],
    keywords: ["dolar", "dólar", "dollar"],
  },
  {
    userFriendlyName: "Euro",
    variations: [
      "ant-design:euro-circle-filled",
      "ant-design:euro-circle-outlined",
      "foundation:euro",
    ],
    keywords: ["euro"],
  },
  {
    userFriendlyName: "Visual Studio",
    variations: [
      "bx:bxl-visual-studio",
      "cib:visual-studio",
      "logos:visual-studio",
      "logos:visual-studio-code",
    ],
    keywords: [
      "visual",
      "studio",
      "visual studio",
      "code",
      "visual code",
      "visual studio code",
      "ide",
    ],
  },
  {
    userFriendlyName: "Notepad++",
    variations: ["simple-icons:notepadplusplus"],
    keywords: ["notepadplusplus", "notepad", "plus"],
  },
  {
    userFriendlyName: "Notepad",
    variations: [
      "bx:bx-notepad",
      "bx:bxs-notepad",
      "fluent:notepad-16-filled",
      "fluent:notepad-16-regular",
    ],
    keywords: ["notepad", "note", "caderno"],
  },
  {
    userFriendlyName: "Calendar",
    variations: [
      "ant-design:calendar-filled",
      "ant-design:calendar-outlined",
      "el:calendar-sign",
      "el:calendar",
    ],
    keywords: ["calendar", "calendário"],
  },
  {
    userFriendlyName: "Clock",
    variations: [
      "akar-icons:clock",
      "ant-design:clock-circle-filled",
      "ep:alarm-clock",
      "clarity:alarm-clock-solid",
    ],
    keywords: [
      "clock",
      "relógio",
      "relogio",
      "time",
      "tempo",
      "hora",
      "horário",
      "horario",
      "timer",
    ],
  },
  {
    userFriendlyName: "Timer",
    variations: [
      "bx:bx-timer",
      "bx:bxs-timer",
      "cil:av-timer",
      "fluent:timer-16-filled",
      "fluent:timer-16-regular",
    ],
    keywords: ["timer", "cronômetro", "cronometro"],
  },
  {
    userFriendlyName: "Android",
    variations: [
      "logos:android-icon",
      "ant-design:android-filled",
      "ic:baseline-android",
      "jam:android-circle",
      "jam:android-square",
    ],
    keywords: ["android"],
  },
  {
    userFriendlyName: "Upload",
    variations: [
      "bx:bxs-cloud-upload",
      "bx:bx-upload",
      "fa-solid:file-upload",
      "jam:android-circle",
      "fluent:arrow-upload-24-filled",
    ],
    keywords: ["upload", "enviar", "subir"],
  },
  {
    userFriendlyName: "Download",
    variations: [
      "bx:bx-cloud-download",
      "bi:download",
      "bx:bxs-download",
      "jam:android-circle",
      "entypo:download",
    ],
    keywords: ["download", "baixar"],
  },
  {
    userFriendlyName: "Smartphone",
    variations: [
      "cil:screen-smartphone",
      "si-glyph:smartphone",
      "zmdi:smartphone-iphone",
      "jam:android-circle",
      "entypo:download",
    ],
    keywords: ["smartphone", "celular", "cel", "phone"],
  },
];

export default icons;
